// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viandas.Infrastructure.Data.Db;

#nullable disable

namespace Viandas.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDb))]
    partial class AppDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Viandas.Infrastructure.Data.EntityModel.DishModel", b =>
                {
                    b.Property<string>("DishID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DishID");

                    b.HasIndex("UserID");

                    b.ToTable("Dishes", (string)null);
                });

            modelBuilder.Entity("Viandas.Infrastructure.Data.EntityModel.MenuModel", b =>
                {
                    b.Property<string>("MenuID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ConsumptionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDeadLine")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserResponsibleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MenuID");

                    b.HasIndex("UserResponsibleId");

                    b.ToTable("Menus", (string)null);
                });

            modelBuilder.Entity("Viandas.Infrastructure.Data.EntityModel.MenuOptionModel", b =>
                {
                    b.Property<string>("MenuID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DishID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("MenuID", "DishID");

                    b.HasIndex("DishID");

                    b.ToTable("MenuOptions", (string)null);
                });

            modelBuilder.Entity("Viandas.Infrastructure.Data.EntityModel.OrderModel", b =>
                {
                    b.Property<string>("OrderID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MenuModelMenuID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderID");

                    b.HasIndex("DiscountID");

                    b.HasIndex("MenuModelMenuID");

                    b.HasIndex("UserID");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("Viandas.Infrastructure.Data.EntityModel.UserModel", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Viandas.Infrastructure.Data.EntityModels.DiscountModel", b =>
                {
                    b.Property<string>("DiscountID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DiscountID");

                    b.HasIndex("UserID");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("Viandas.Infrastructure.Data.EntityModels.OrderItemModel", b =>
                {
                    b.Property<string>("OrderID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MenuID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DishID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderModelOrderID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("OrderID", "MenuID", "DishID");

                    b.HasIndex("OrderModelOrderID");

                    b.ToTable("itemsDeOrdenes", (string)null);
                });

            modelBuilder.Entity("Viandas.Infrastructure.Data.EntityModel.DishModel", b =>
                {
                    b.HasOne("Viandas.Infrastructure.Data.EntityModel.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Viandas.Infrastructure.Data.EntityModel.MenuModel", b =>
                {
                    b.HasOne("Viandas.Infrastructure.Data.EntityModel.UserModel", "Responsible")
                        .WithMany()
                        .HasForeignKey("UserResponsibleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("Viandas.Infrastructure.Data.EntityModel.MenuOptionModel", b =>
                {
                    b.HasOne("Viandas.Infrastructure.Data.EntityModel.DishModel", "Dish")
                        .WithMany()
                        .HasForeignKey("DishID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Viandas.Infrastructure.Data.EntityModel.MenuModel", "Menu")
                        .WithMany("Options")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Viandas.Infrastructure.Data.EntityModel.OrderModel", b =>
                {
                    b.HasOne("Viandas.Infrastructure.Data.EntityModels.DiscountModel", "Discount")
                        .WithMany()
                        .HasForeignKey("DiscountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viandas.Infrastructure.Data.EntityModel.MenuModel", null)
                        .WithMany("Orders")
                        .HasForeignKey("MenuModelMenuID");

                    b.HasOne("Viandas.Infrastructure.Data.EntityModel.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Viandas.Infrastructure.Data.EntityModels.DiscountModel", b =>
                {
                    b.HasOne("Viandas.Infrastructure.Data.EntityModel.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Viandas.Infrastructure.Data.EntityModels.OrderItemModel", b =>
                {
                    b.HasOne("Viandas.Infrastructure.Data.EntityModel.OrderModel", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderModelOrderID");
                });

            modelBuilder.Entity("Viandas.Infrastructure.Data.EntityModel.MenuModel", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Viandas.Infrastructure.Data.EntityModel.OrderModel", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
